FROM rust:1.65-bullseye
COPY . .
RUN apt-get update && apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev -y
RUN rustup target add wasm32-unknown-unknown
#RUN wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
RUN cargo install --locked trunk
RUN trunk build --release
EXPOSE 8080
CMD [ "trunk","serve","--release","--address","0.0.0.0"]
